[project]
name = "test-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "duckdb>=1.4.3",
    "langgraph>=1.0.5",
    "ollama>=0.6.1",
    "streamlit>=1.52.2",
]
